### ISSUE TITLE
Keep Databases expanded

### ISSUE THREAD

**Issue by roablep** [RedisInsight/Redis-for-VS-Code#217]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Let's say I'm debugging something. I will have a Redis DB selected and expanded. 
Currently when I navigate away from the tab, all the folders collapse. 
When I navigate back I have to expand again.
<img width="90" alt="image" src="https://github.com/user-attachments/assets/5f280f74-25af-4bb6-9bb3-26aadec8a035">

Ideally: Keep them in the expanded position by default

**How often do you encounter this problem** (Describe how frequently this problem occurs).
All the time

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi @roablep , this is added with 1.2.0 (released today).
