### ISSUE TITLE
Auto Refresh

### ISSUE THREAD

**Issue by roablep** [RedisInsight/Redis-for-VS-Code#218]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Does the plugin have an auto refresh setting like in Redis Insight?
<img width="133" alt="image" src="https://github.com/user-attachments/assets/aad69f82-b59c-4654-8241-9f91b9ad62c5">

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
@roablep , not yet, but we'll add it in one of our upcoming releases.

**Comment by ViktarStarastsenka** [comment]
@roablep ,  this has been added with 1.2.0 (released today).
