### ISSUE TITLE
add support for msgpack

### ISSUE THREAD

**Issue by omencat** [RedisInsight/Redis-for-VS-Code#244]
Presented with the following when clicking on a topic:
```
This data type is not currently supported.
See our repository for the list of [supported data types.](https://github.com/RedisInsight/Redis-for-VS-Code/)
```

We are currently using msgpack for encoding our streams. Is it possible to add support for msgpack for this extension?

**Comment by ViktarStarastsenka** [comment]
hi @omencat , Redis for VS Code supports msgpack, but it does not currently support streams.
here is a ticket for that - https://github.com/RedisInsight/Redis-for-VS-Code/issues/216.

**Comment by omencat** [comment]
ok, thanks for the clarification
